DATADIR: '/home/lhernandez2/Venus_SAR/Dataset/'
TEST_IMGDIR: 'val_images'
TEST_SEGDIR: 'val_labels'
IFRAG: ''
SFRAG: ''
IMFIX: '.png'
LABFIX: '.png'
MODEL_LOCATION: "/home/lhernandez2/Venus_SAR/Dataset/Save/weights_train_20241001_121744/"
NUM_INFERENCES_SHOW: 3
